document.addEventListener('DOMContentLoaded', async () => {
  const body=document.body, sidebar=document.querySelector('.sidebar'), content=document.getElementById('content-display'), toggle=document.getElementById('menu-toggle'), theme=document.getElementById('theme-switcher');
  const lessonPath=location.pathname.replace('/articles/lessons/','/articles/');
  const isCompose=lessonPath.includes('/content-compose/');
  const isOop=lessonPath.includes('/content-kotlin/oop/');
  const hub=isCompose?'/articles/jetpack-compose.html':(isOop?'/articles/oop_kotlin.html':'/articles/kotlin.html');
  const courseName=isCompose?'Jetpack Compose':(isOop?'Kotlin OOP':'Kotlin');
  document.querySelector('.header h1').textContent=courseName;
  const canonical='https://talhajalvi.com'+location.pathname;
  let link=document.querySelector('link[rel="canonical"]'); if(!link){link=document.createElement('link');link.rel='canonical';document.head.appendChild(link)} link.href=canonical;
  function close(){sidebar?.classList.remove('open');body.classList.remove('sidebar-open');toggle?.setAttribute('aria-expanded','false')}
  function setupMobile(){if(!sidebar)return; if(!document.querySelector('.sidebar-backdrop')){const b=document.createElement('div');b.className='sidebar-backdrop';b.addEventListener('click',close);body.appendChild(b)} toggle?.addEventListener('click',()=>{const open=sidebar.classList.toggle('open');body.classList.toggle('sidebar-open',open);toggle.setAttribute('aria-expanded',String(open))});document.addEventListener('keydown',e=>e.key==='Escape'&&close())}
  function enhanceSidebar(){if(!sidebar||sidebar.dataset.enhanced)return;sidebar.dataset.enhanced='1';const list=sidebar.querySelector('.sidebar-menu, ul');if(!list)return;const tools=document.createElement('div');tools.className='sidebar-tools';tools.innerHTML='<a class="sidebar-home" href="/articles/articles-home.html">← All learning paths</a><input class="sidebar-filter" type="search" placeholder="Filter topics…" aria-label="Filter course topics">';sidebar.prepend(tools);let currentGroup=null;[...list.children].forEach(li=>{if(li.classList.contains('menu-section')){const d=document.createElement('details');d.className='sidebar-group';const s=document.createElement('summary');s.textContent=li.textContent.trim();const ul=document.createElement('ul');ul.className='sidebar-group-list';d.append(s,ul);list.insertBefore(d,li);li.remove();currentGroup=d}else if(currentGroup&&!li.classList.contains('menu-title')) currentGroup.querySelector('ul').appendChild(li)});const links=[...sidebar.querySelectorAll('.nav-link')];links.forEach(a=>{const raw=a.getAttribute('href')||'';if(raw.includes('content-kotlin/')||raw.includes('content-compose/')){const normalized=new URL(raw,hub.startsWith('/')?location.origin+hub:location.href).pathname;a.href='/articles/lessons/'+normalized.replace(/^\/articles\//,'')}if(a.pathname===location.pathname){a.classList.add('active');a.setAttribute('aria-current','page');a.closest('details')?.setAttribute('open','')}});const groups=[...sidebar.querySelectorAll('.sidebar-group')];if(!groups.some(g=>g.open)&&groups[0])groups[0].open=true;tools.querySelector('input').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();let any=false;groups.forEach(g=>{let hits=0;g.querySelectorAll('a').forEach(a=>{const show=!q||a.textContent.toLowerCase().includes(q);a.closest('li').hidden=!show;if(show)hits++});g.hidden=!!q&&!hits;if(q&&hits)g.open=true;any ||= hits>0});let empty=sidebar.querySelector('.sidebar-empty');if(q&&!any){if(!empty){empty=document.createElement('div');empty.className='sidebar-empty';empty.textContent='No matching topics';sidebar.appendChild(empty)}}else empty?.remove()})}
  try{const hubHtml=await fetch(hub).then(r=>{if(!r.ok)throw new Error(r.status);return r.text()});const doc=new DOMParser().parseFromString(hubHtml,'text/html');const sourceSidebar=doc.querySelector('.sidebar');if(sourceSidebar&&sidebar){sidebar.innerHTML=sourceSidebar.innerHTML;enhanceSidebar()}}catch(e){console.error('Could not load course navigation',e)}
  try{const html=await fetch(lessonPath).then(r=>{if(!r.ok)throw new Error(r.status);return r.text()});content.innerHTML=html;const heading=content.querySelector('h1,h2');if(heading){document.title=heading.textContent.trim()+' | Talha Learning';document.querySelector('.header h1').textContent=heading.textContent.trim()}content.removeAttribute('aria-busy')}catch(e){content.innerHTML='<div class="error-message-container"><p>This lesson is not available yet.</p></div>';console.error(e)}
  setupMobile();
  const setTheme=t=>{body.classList.toggle('dark-mode',t==='dark');if(theme)theme.textContent=t==='dark'?'Light mode':'Dark mode'};let saved='light';try{saved=localStorage.getItem('theme')||'light'}catch(_){}setTheme(saved);theme?.addEventListener('click',()=>{const n=body.classList.contains('dark-mode')?'light':'dark';setTheme(n);try{localStorage.setItem('theme',n)}catch(_){}});
});
